### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Voidisendless**
Added use of chat now button, added privacy policy to website

### CODE REVIEW

**Comment by probablytaylors** [comment]
You have managed to mess up your code by the way, it looks written by ChatGPT. anyone at Google would be pissed to see that messy code, Fix your code and reformat it. very un-neat. and very unkept, also you cant have a jobs page if the owner is Under the age of 18, it's illegal in CA & US.

**Comment by EricPanDev** [comment]
@Osinted no one gives a shit, shut up before I submit logs of everything you've said to github and discord.

This website was also not made by me, and you don't work for google nor discord.

**Comment by SnowoCowone** [comment]
very bad website !!!!!!!! /jk

**Comment by passthepizza** [comment]
but everyone said the website looks nice :(

**Pull request merged**
